kiboko_social_network_messenger_new_message:
    path:  /new
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\MessengerController::newAction' }

kiboko_social_network_messenger_remove_message:
    path:  /{msgId}/remove
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\MessengerController::removeAction' }
    requirements:
        msgId:  \d+

kiboko_social_network_messenger_reply_message:
    path:  /{msgId}/reply
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\MessengerController::showAction' }
    requirements:
        msgId:  \d+

kiboko_social_network_messenger_show_message:
    path:  /{msgId}/
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\MessengerController::showAction' }
    requirements:
        msgId:  \d+

kiboko_social_network_messenger_list:
    path:  /
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\MessengerController::listAction' }
