kiboko_social_network_messenger_new_message:
    path:  /new
    defaults: { _controller: KibokoSocialNetworkBundle:Messenger:new }

kiboko_social_network_messenger_remove_message:
    path:  /{msgId}/remove
    defaults: { _controller: KibokoSocialNetworkBundle:Messenger:remove }
    requirements:
        msgId:  \d+

kiboko_social_network_messenger_reply_message:
    path:  /{msgId}/reply
    defaults: { _controller: KibokoSocialNetworkBundle:Messenger:show }
    requirements:
        msgId:  \d+

kiboko_social_network_messenger_show_message:
    path:  /{msgId}/
    defaults: { _controller: KibokoSocialNetworkBundle:Messenger:show }
    requirements:
        msgId:  \d+

kiboko_social_network_messenger_list:
    path:  /
    defaults: { _controller: KibokoSocialNetworkBundle:Messenger:list }
