kiboko_social_network_admin_users:
    path:  /
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:list }

kiboko_social_network_admin_users_ban:
    path:  /{userId}/ban
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:ban }

kiboko_social_network_admin_users_unban:
    path:  /{userId}/unban
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:ban }

kiboko_social_network_admin_users_remove_avatar:
    path:  /{userId}/remove_avatar
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:removeAvatar }

kiboko_social_network_admin_users_init_password:
    path:  /{userId}/init-password
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:initPassword }

kiboko_social_network_admin_users_contact:
    path:  /{userId}/contact
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:contact }

kiboko_social_network_admin_users_add:
    path:  /add
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:add }

kiboko_social_network_admin_users_edit:
    path:  /{userId}/edit
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:add }

kiboko_social_network_admin_users_remove:
    path:  /{userId}/remove
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:remove }

kiboko_social_network_admin_users_view:
    path:  /{userId}/view
    defaults: { _controller: KibokoSocialNetworkBundle:AdminUser:view }
