kiboko_social_network_admin_users:
    path:  /
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::listAction' }

kiboko_social_network_admin_users_ban:
    path:  /{userId}/ban
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::banAction' }

kiboko_social_network_admin_users_unban:
    path:  /{userId}/unban
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::banAction' }

kiboko_social_network_admin_users_remove_avatar:
    path:  /{userId}/remove_avatar
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::removeAvatarAction' }

kiboko_social_network_admin_users_init_password:
    path:  /{userId}/init-password
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::initPasswordAction' }

kiboko_social_network_admin_users_contact:
    path:  /{userId}/contact
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::contactAction' }

kiboko_social_network_admin_users_add:
    path:  /add
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::addAction' }

kiboko_social_network_admin_users_edit:
    path:  /{userId}/edit
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::addAction' }

kiboko_social_network_admin_users_remove:
    path:  /{userId}/remove
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::removeAction' }

kiboko_social_network_admin_users_view:
    path:  /{userId}/view
    defaults: { _controller: 'Kiboko\Bundle\SocialNetworkBundle\Controller\AdminUserController::viewAction' }
