services:
    # Twig
    kiboko_social_network.twig.avatar_extension:
        class: Kiboko\Bundle\SocialNetworkBundle\Twig\Extension\AvatarExtension
        tags:
            -  { name: 'twig.extension' }

    kiboko_social_network.twig.friendship_extension:
        class: Kiboko\Bundle\SocialNetworkBundle\Twig\Extension\FriendshipExtension
        arguments:
            doctrine: '@doctrine'
        tags:
            -  { name: 'twig.extension' }

    kiboko_social_network.twig.login_form_extension:
        class: Kiboko\Bundle\SocialNetworkBundle\Twig\Extension\LoginFormExtension
        arguments:
            session:       '@session'
            csrf_provider: '@security.csrf.token_manager'
        tags:
            -  { name: 'twig.extension' }

    kiboko_social_network.twig.messenger_extension:
        class: Kiboko\Bundle\SocialNetworkBundle\Twig\Extension\MessengerExtension
        arguments:
            doctrine: '@doctrine'
        tags:
            -  { name: 'twig.extension' }

    kiboko_social_network.registration.form.type:
        class: Kiboko\Bundle\SocialNetworkBundle\Form\Type\RegistrationFormType
        arguments: [ '%fos_user.model.user.class%' ]
        tags:
            - { name: 'form.type', alias: 'kiboko_social_network_registration_type' }

    kiboko_social_network.resetting.form.type:
        class: Kiboko\Bundle\SocialNetworkBundle\Form\Type\ResettingFormType
        tags:
            - { name: 'form.type', alias: 'kiboko_social_network_resetting_type' }

    kiboko_social_network.profile.form.type:
        class: Kiboko\Bundle\SocialNetworkBundle\Form\Type\ProfileFormType
        arguments:
          - '%fos_user.model.user.class%'
        tags:
            - { name: 'form.type', alias: 'kiboko_social_network_profile_type' }

    kiboko_social_network.profile.form.handler:
        class: Kiboko\Bundle\SocialNetworkBundle\Form\Handler\ProfileFormHandler
        scope: request
        arguments:
            - '@fos_user.profile.form'
            - '@request'
            - '@fos_user.user_manager'

    # Contact mailer
    kiboko_social_network.contact_mailer:
        class: Kiboko\Bundle\SocialNetworkBundle\Mailer\ContactMailer
        arguments:
            - '@mailer'
            - '@router'
            - '@templating'
            -
                admin.from:          '%kiboko_social_network.contact.admin.email.from%'
                admin.from_name:     '%kiboko_social_network.contact.admin.email.from_name%'
                admin.template.text: '%kiboko_social_network.contact.admin.email.text%'
                admin.template.html: '%kiboko_social_network.contact.admin.email.html%'
                admin.template.msn:  '%kiboko_social_network.contact.admin.email.msn%'
        calls:
            - [ setMessenger, [ '@kiboko_social_network.messenger.messagebox' ] ]

    # Avatar mailer
    kiboko_social_network.avatar_mailer:
        class: Kiboko\Bundle\SocialNetworkBundle\Mailer\AvatarMailer
        arguments:
            - '@mailer'
            - '@router'
            - '@templating'
            -
                admin.from:          '%kiboko_social_network.avatar.admin.remove.email.from%'
                admin.from_name:     '%kiboko_social_network.avatar.admin.remove.email.from_name%'
                admin.subject:       '%kiboko_social_network.avatar.admin.remove.email.subject%'
                admin.template.text: '%kiboko_social_network.avatar.admin.remove.email.text%'
                admin.template.html: '%kiboko_social_network.avatar.admin.remove.email.html%'
                admin.template.msn:  '%kiboko_social_network.avatar.admin.remove.email.msn%'
        calls:
            - [ setMessenger, [ '@kiboko_social_network.messenger.messagebox' ] ]

    # Friendship mail
    kiboko_social_network.friendship_mailer:
        class: Kiboko\Bundle\SocialNetworkBundle\Mailer\FriendshipMailer
        arguments:
            - '@mailer'
            - '@router'
            - '@templating'
            -
                from:                 '%kiboko_social_network.friendship.email.from%'
                from_name:            '%kiboko_social_network.friendship.email.from_name%'
                invit.subject:        '%kiboko_social_network.friendship.email.invit.subject%'
                invit.template.text:  '%kiboko_social_network.friendship.email.invit.text%'
                invit.template.html:  '%kiboko_social_network.friendship.email.invit.html%'
                invit.template.msn:   '%kiboko_social_network.friendship.email.invit.msn%'
                accept.subject:       '%kiboko_social_network.friendship.email.accept.subject%'
                accept.template.text: '%kiboko_social_network.friendship.email.accept.text%'
                accept.template.html: '%kiboko_social_network.friendship.email.accept.html%'
                accept.template.msn:  '%kiboko_social_network.friendship.email.accept.msn%'
                refuse.subject:       '%kiboko_social_network.friendship.email.refuse.subject%'
                refuse.template.text: '%kiboko_social_network.friendship.email.refuse.text%'
                refuse.template.html: '%kiboko_social_network.friendship.email.refuse.html%'
                refuse.template.msn:  '%kiboko_social_network.friendship.email.refuse.msn%'
                remove.subject:       '%kiboko_social_network.friendship.email.remove.subject%'
                remove.template.text: '%kiboko_social_network.friendship.email.remove.text%'
                remove.template.html: '%kiboko_social_network.friendship.email.remove.html%'
                remove.template.msn:  '%kiboko_social_network.friendship.email.remove.msn%'
        calls:
            - [ setMessenger, [ '@kiboko_social_network.messenger.messagebox' ] ]

    # FOS mailer override
    kiboko_social_network.fos_mailer:
        class: Kiboko\Bundle\SocialNetworkBundle\Mailer\FosMailer
        arguments:
            0: '@mailer'
            1: '@router'
            2: '@templating'
            3:
                registration.from_mail     : %fos_user.registration.confirmation.from_email%
                registration.subject       : %kiboko_social_network.registration.email.subject%
                registration.template.text : %kiboko_social_network.registration.email.text%
                registration.template.html : %kiboko_social_network.registration.email.html%
                confirmation.from_mail     : %fos_user.registration.confirmation.from_email%
                confirmation.subject       : %kiboko_social_network.confirmation.email.subject%
                confirmation.template.text : %kiboko_social_network.confirmation.email.text%
                confirmation.template.html : %kiboko_social_network.confirmation.email.html%
                resetting.from_mail        : %fos_user.resetting.email.from_email%
                resetting.subject          : %kiboko_social_network.resetting.email.subject%
                resetting.template.text     : %kiboko_social_network.resetting.email.text%
                resetting.template.html    : %kiboko_social_network.resetting.email.html%

    # Messenger mailer
    kiboko_social_network.messenger_mailer:
        class: Kiboko\Bundle\SocialNetworkBundle\Mailer\MessengerMailer
        arguments:
            0: '@mailer'
            1: '@router'
            2: '@templating'
            3:
                message.from          : %kiboko_social_network.messenger.message.email.from%
                message.from_name     : %kiboko_social_network.messenger.message.email.from_name%
                message.subject       : %kiboko_social_network.messenger.message.email.subject%
                message.template.text : %kiboko_social_network.messenger.message.email.text%
                message.template.html : %kiboko_social_network.messenger.message.email.html%
                answer.from           : %kiboko_social_network.messenger.answer.email.from%
                answer.from_name      : %kiboko_social_network.messenger.answer.email.from_name%
                answer.subject        : %kiboko_social_network.messenger.answer.email.subject%
                answer.template.text  : %kiboko_social_network.messenger.answer.email.text%
                answer.template.html  : %kiboko_social_network.messenger.answer.email.html%
        calls:
            - [ setMessenger, [ '@kiboko_social_network.messenger.messagebox' ] ]

    # Messenger service
    kiboko_social_network.messenger.messagebox:
        class: Kiboko\Bundle\SocialNetworkBundle\Service\Messenger
        arguments:
            doctrine: '@doctrine'
            securityContext: '@security.context'
